application: blankbracket
version: '0'
runtime: python27
api_version: 1
threadsafe: 1

handlers:
- url: /stylesheets
  static_dir: public/stylesheets
- url: /js
  static_dir: public/js
- url: /qunit
  static_dir: public/qunit
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest